version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
      - echo Listing files before artifacts...
      - ls -la
      - echo Copying deployment files...
      - cp appspec.yml build/
      - cp -r scripts build/
      - echo Final build directory contents...
      - ls -la build/

artifacts:
  files:
    - "**/*"
  base-directory: build
  name: react-app-build
